{
 "title": "Device Configuration",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Sensors",
    "query": "SHOW TAG VALUES FROM messages\n WITH  KEY = \"name\""
   },
   {
    "name": "Topic",
    "query": "SHOW TAG VALUES WITH KEY = \"channel\""
   },
   {
    "name": "Publisher",
    "label": "ID",
    "query": "SHOW TAG VALUES FROM messages WITH KEY = \"publisher\" WHERE \"devname\" =~ /^$Device$/"
   },
   { "name": "DB", "query": "influxdb" },
   { "name": "time_off_sec", "query": "${VAR_TIME_OFF_SEC}" },
   {
    "name": "Device",
    "label": "Dispositius",
    "query": "SHOW TAG VALUES FROM messages WITH KEY = \"devname\" "
   },
   {
    "name": "Unit",
    "query": "SHOW TAG VALUES FROM messages WITH KEY = \"unit\" WHERE \"name\" =~ /^$Sensors$/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "----\n## Open Digital Aquaculture\n----\n Per device sensor status and sensor sampling rate configuration. Select the device you want to configure from the drop-down list.\n\n"
   },
   "content": "----\n## Open Digital Aquaculture\n----\n Per device sensor status and sensor sampling rate configuration. Select the device you want to configure from the drop-down list.\n\n"
  },
  {
   "title": "System heatlh",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Sensors",
     "type": "stat",
     "description": "Shows if sensor have been active within the last 120 seconds",
     "gridPos": { "h": 3, "w": 2.1818181818181817, "x": 0, "y": 4 },
     "repeat": "Sensors",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "messages",
       "query": "SELECT \"value\" FROM \"messages\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) AND time >= now() - 120s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "stat",
     "description": "Shows if sensor have been active within the last 120 seconds",
     "gridPos": { "h": 3, "w": 2.1818181818181817, "x": 2.1818181818181817, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "messages",
       "query": "SELECT \"value\" FROM \"messages\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) AND time >= now() - 120s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "stat",
     "description": "Shows if sensor have been active within the last 120 seconds",
     "gridPos": { "h": 3, "w": 2.1818181818181817, "x": 4.363636363636363, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "messages",
       "query": "SELECT \"value\" FROM \"messages\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) AND time >= now() - 120s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "stat",
     "description": "Shows if sensor have been active within the last 120 seconds",
     "gridPos": { "h": 3, "w": 2.1818181818181817, "x": 6.545454545454545, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "messages",
       "query": "SELECT \"value\" FROM \"messages\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) AND time >= now() - 120s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "stat",
     "description": "Shows if sensor have been active within the last 120 seconds",
     "gridPos": { "h": 3, "w": 2.1818181818181817, "x": 8.727272727272727, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "messages",
       "query": "SELECT \"value\" FROM \"messages\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) AND time >= now() - 120s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "stat",
     "description": "Shows if sensor have been active within the last 120 seconds",
     "gridPos": { "h": 3, "w": 2.1818181818181817, "x": 10.909090909090908, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "messages",
       "query": "SELECT \"value\" FROM \"messages\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) AND time >= now() - 120s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "stat",
     "description": "Shows if sensor have been active within the last 120 seconds",
     "gridPos": { "h": 3, "w": 2.1818181818181817, "x": 13.09090909090909, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "messages",
       "query": "SELECT \"value\" FROM \"messages\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) AND time >= now() - 120s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "stat",
     "description": "Shows if sensor have been active within the last 120 seconds",
     "gridPos": { "h": 3, "w": 2.1818181818181817, "x": 15.272727272727272, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "messages",
       "query": "SELECT \"value\" FROM \"messages\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) AND time >= now() - 120s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "stat",
     "description": "Shows if sensor have been active within the last 120 seconds",
     "gridPos": { "h": 3, "w": 2.1818181818181817, "x": 17.454545454545453, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "messages",
       "query": "SELECT \"value\" FROM \"messages\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) AND time >= now() - 120s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "stat",
     "description": "Shows if sensor have been active within the last 120 seconds",
     "gridPos": { "h": 3, "w": 2.1818181818181817, "x": 19.636363636363633, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "messages",
       "query": "SELECT \"value\" FROM \"messages\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) AND time >= now() - 120s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "stat",
     "description": "Shows if sensor have been active within the last 120 seconds",
     "gridPos": { "h": 3, "w": 2.1818181818181817, "x": 21.818181818181813, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "messages",
       "query": "SELECT \"value\" FROM \"messages\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) AND time >= now() - 120s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Timeseries data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Sensors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "repeat": "Sensors",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device, $Sensors [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device, $Sensors [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device, $Sensors [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device, $Sensors [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device, $Sensors [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device, $Sensors [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device, $Sensors [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device, $Sensors [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device, $Sensors [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device, $Sensors [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device, $Sensors [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current sampling rate of $Sensors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
     "repeat": "Sensors",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "Sampling Rate",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 9 },
     "repeat": "Sensors",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current sampling rate of $Sensors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "Sampling Rate",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 12 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current sampling rate of $Sensors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "Sampling Rate",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 15 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current sampling rate of $Sensors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "Sampling Rate",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 18 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current sampling rate of $Sensors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "Sampling Rate",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 21 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current sampling rate of $Sensors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "Sampling Rate",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 24 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current sampling rate of $Sensors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "Sampling Rate",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 27 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current sampling rate of $Sensors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "Sampling Rate",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 30 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current sampling rate of $Sensors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "Sampling Rate",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 33 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current sampling rate of $Sensors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "Sampling Rate",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 36 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current sampling rate of $Sensors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "Sampling Rate",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 39 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}