{
 "title": "Alertes",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DB", "query": "influxdb" },
   {
    "name": "Topic",
    "query": "SHOW TAG VALUES WITH KEY=\"channel\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "----\n## Aqüicultura Digital Oberta\n----\nShows the configured alerts for the devices\n\n"
   },
   "content": "----\n## Aqüicultura Digital Oberta\n----\nEs mostren les alertes de temperatura del dispositiu.\n\n"
  },
  {
   "title": "Historical",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature-S",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature-S [Cel] ",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
     "repeat": "Sensors",
     "yaxes": [
      { "format": "short", "label": "Celsius" }
     ],
     "targets": [
      {
       "alias": "[[tag_devname]]",
       "groupBy": [
        { "params": [ "devname" ], "type": "tag" }
       ],
       "measurement": "messages",
       "query": "SELECT mean(\"value\") FROM \"messages\" WHERE (\"name\" = 'Temperature-S') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Temperature-S" }
       ]
      }
     ]
    },
    {
     "title": "Set Alarm Limits",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "AirCO2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "AirCO2 [ppm]",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 25 },
     "repeat": "Sensors",
     "yaxes": [
      { "format": "short", "label": "Celsius" }
     ],
     "targets": [
      {
       "alias": "[[tag_devname]]",
       "groupBy": [
        { "params": [ "devname" ], "type": "tag" }
       ],
       "measurement": "messages",
       "query": "SELECT mean(\"value\") FROM \"messages\" WHERE (\"name\" = 'Temperature') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "AirCO2" }
       ]
      }
     ]
    },
    {
     "title": "Set Alarm Limits",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "WaterLevel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "WaterLevel",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
     "repeat": "Sensors",
     "yaxes": [
      { "format": "short", "label": "Celsius" }
     ],
     "targets": [
      {
       "alias": "[[tag_devname]]",
       "groupBy": [
        { "params": [ "devname" ], "type": "tag" }
       ],
       "measurement": "messages",
       "query": "SELECT mean(\"value\") FROM \"messages\" WHERE (\"name\" = 'Temperature') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "WaterLevel" }
       ]
      }
     ]
    },
    {
     "title": "Set Alarm Limits",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Oxygen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oxygen [mg/L]",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
     "repeat": "Sensors",
     "yaxes": [
      { "format": "short", "label": "Celsius" }
     ],
     "targets": [
      {
       "alias": "[[tag_devname]]",
       "groupBy": [
        { "params": [ "devname" ], "type": "tag" }
       ],
       "measurement": "messages",
       "query": "SELECT mean(\"value\") FROM \"messages\" WHERE (\"name\" = 'Temperature') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Oxygen" }
       ]
      }
     ]
    },
    {
     "title": "Set Alarm Limits",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "AtmosphericTemp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "AtmosphericTemp [Cel]",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
     "repeat": "Sensors",
     "yaxes": [
      { "format": "short", "label": "Celsius" }
     ],
     "targets": [
      {
       "alias": "[[tag_devname]]",
       "groupBy": [
        { "params": [ "devname" ], "type": "tag" }
       ],
       "measurement": "messages",
       "query": "SELECT mean(\"value\") FROM \"messages\" WHERE (\"name\" = 'Temperature') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "AtmosphericTemp" }
       ]
      }
     ]
    },
    {
     "title": "Set Alarm Limits",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Conductivity2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conductivity2 [ms/cm]",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 25 },
     "repeat": "Sensors",
     "yaxes": [
      { "format": "short", "label": "Celsius" }
     ],
     "targets": [
      {
       "alias": "[[tag_devname]]",
       "groupBy": [
        { "params": [ "devname" ], "type": "tag" }
       ],
       "measurement": "messages",
       "query": "SELECT mean(\"value\") FROM \"messages\" WHERE (\"name\" = 'Temperature') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Conductivity2" }
       ]
      }
     ]
    },
    {
     "title": "Set Alarm Limits",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Conductivity1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conductivity1 [ms/cm]",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
     "repeat": "Sensors",
     "yaxes": [
      { "format": "short", "label": "Celsius" }
     ],
     "targets": [
      {
       "alias": "[[tag_devname]]",
       "groupBy": [
        { "params": [ "devname" ], "type": "tag" }
       ],
       "measurement": "messages",
       "query": "SELECT mean(\"value\") FROM \"messages\" WHERE (\"name\" = 'Temperature') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Conductivity1" }
       ]
      }
     ]
    },
    {
     "title": "Set Alarm Limits",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Turbidity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Turbidity [NTU]",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 27 },
     "repeat": "Sensors",
     "yaxes": [
      { "format": "short", "label": "Celsius" }
     ],
     "targets": [
      {
       "alias": "[[tag_devname]]",
       "groupBy": [
        { "params": [ "devname" ], "type": "tag" }
       ],
       "measurement": "messages",
       "query": "SELECT mean(\"value\") FROM \"messages\" WHERE (\"name\" = 'Temperature') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Turbidity" }
       ]
      }
     ]
    },
    {
     "title": "Set Alarm Limits",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "pH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "pH",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
     "repeat": "Sensors",
     "yaxes": [
      { "format": "short", "label": "Celsius" }
     ],
     "targets": [
      {
       "alias": "[[tag_devname]]",
       "groupBy": [
        { "params": [ "devname" ], "type": "tag" }
       ],
       "measurement": "messages",
       "query": "SELECT mean(\"value\") FROM \"messages\" WHERE (\"name\" = 'Temperature') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "pH" }
       ]
      }
     ]
    },
    {
     "title": "Set Alarm Limits",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Humidity [%]",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
     "repeat": "Sensors",
     "yaxes": [
      { "format": "short", "label": "Celsius" }
     ],
     "targets": [
      {
       "alias": "[[tag_devname]]",
       "groupBy": [
        { "params": [ "devname" ], "type": "tag" }
       ],
       "measurement": "messages",
       "query": "SELECT mean(\"value\") FROM \"messages\" WHERE (\"name\" = 'Temperature') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Humidity" }
       ]
      }
     ]
    },
    {
     "title": "Set Alarm Limits",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature-D",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature-D [Cel]",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 30 },
     "repeat": "Sensors",
     "yaxes": [
      { "format": "short", "label": "Celsius" }
     ],
     "targets": [
      {
       "alias": "[[tag_devname]]",
       "groupBy": [
        { "params": [ "devname" ], "type": "tag" }
       ],
       "measurement": "messages",
       "query": "SELECT mean(\"value\") FROM \"messages\" WHERE (\"name\" = 'Temperature') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Temperature-D" }
       ]
      }
     ]
    },
    {
     "title": "Set Alarm Limits",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}