{
 "title": "Calibration",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DB", "query": "influxdb" },
   {
    "name": "Topic",
    "query": "SHOW TAG VALUES WITH KEY = \"channel\""
   },
   {
    "name": "Publisher",
    "label": "ID",
    "query": "SHOW TAG VALUES FROM messages WITH KEY=\"publisher\" WHERE \"devname\" =~ /^$Device$/"
   },
   {
    "name": "Device",
    "label": "Device",
    "query": "SHOW TAG VALUES FROM messages WITH KEY=\"devname\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "----\n## Open Digital Aquaculture\n----\nSelect the device you want to calibrate from the drop-down list and follow the instructions for each of its sensors. You should set the sampling rate for the sensors of this device to a value of 5s, to be able to see real-time changes while you calibrate."
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air CO2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Air CO2 Calibration",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "AirCO2",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 9, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$Device, [[tag_name]] [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "AirCO2" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Dissolved Oxygen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dissolved Oxygen Calibration",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 20, "w": 9, "x": 0, "y": 2 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Dissolved Oxygen",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 9, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$Device, [[tag_name]] [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Oxygen" }
       ]
      }
     ]
    },
    {
     "title": "Temperature-S",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 9, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$Device, [[tag_name]] [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Temperature-S" }
       ]
      }
     ]
    },
    {
     "title": "Low temperature",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 9, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"publisher\" =~ /^$Publisher$/ AND \"name\" = 'Oxygen-db2') ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Oxygen-db2" }
       ]
      }
     ]
    },
    {
     "title": "High temperature",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 15, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"publisher\" =~ /^$Publisher$/ AND \"name\" = 'Oxygen-db1') ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Oxygen-db1" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Conductivity 10-100ms/cm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conductivity Calibration",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Conductivity 10-100 ms/cm",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 9, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$Device, [[tag_name]] [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Conductivity2" }
       ]
      }
     ]
    },
    {
     "title": "12.88 ms/cm",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 9, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT \"value\" FROM \"control\" WHERE (\"publisher\" =~ /^$Publisher$/ AND \"name\" = 'Conductivity2-db1')",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Conductivity2-db1" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Conductivity 1-15 ms/cm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conductivity Calibration",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 4 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Conductivity 1-15 ms/cm",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 9, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$Device, [[tag_name]] [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Conductivity1" }
       ]
      }
     ]
    },
    {
     "title": "1413 us/cm",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 9, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT \"value\" FROM \"control\" WHERE (\"publisher\" =~ /^$Publisher$/ AND \"name\" = 'Conductivity1-db1') ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Conductivity1-db1" }
       ]
      }
     ]
    },
    {
     "title": "12.88 ms/cm",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 15, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT \"value\" FROM \"control\" WHERE (\"publisher\" =~ /^$Publisher$/ AND \"name\" = 'Conductivity1-db2')",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "Conductivity1-db2" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "pH",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "pH Calibration",
     "type": "ryantxu-ajax-panel",
     "gridPos": { "h": 11, "w": 9, "x": 0, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "pH",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 9, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$Device, [[tag_name]] [ [[tag_unit]] ]",
       "groupBy": [
        { "params": [ "unit" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "pH" }
       ]
      }
     ]
    },
    {
     "title": "pH 7.0",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 9, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"publisher\" =~ /^$Publisher$/ AND \"name\" = 'pH-db1') \n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "pH-db1" }
       ]
      }
     ]
    },
    {
     "title": "pH 4.0",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 15, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "measurement": "control",
       "query": "SELECT \"value\" FROM \"control\" WHERE (\"publisher\" =~ /^$Publisher$/ AND \"name\" = 'pH-db2') ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" },
        { "condition": "AND", "key": "name", "operator": "=", "value": "pH-db2" }
       ]
      }
     ]
    }
   ]
  }
 ]
}